function rearrange_welch_periodogram(XData1, YData1,cor_color)
%CREATEFIGURE(XDATA1,YDATA1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 28-Aug-2015 11:16:49

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTickLabel','',...
    'XTickLabel',['150.0';'120.0';'100.0';' 85.7';' 75.0';' 66.7';' 60.0';' 45.0';' 36.0';' 30.0';' 24.0';' 20.0';' 15.0';' 12.0';' 10.0';'  8.6';'  7.5';'  6.7';'  6.0';'  5.5';'  5.0';'  4.6';'  4.3';'  4.0';'  3.8';'  3.5';'  3.3';'  3.2';'  3.0'],...
    'XTick',[0.4 0.5 0.6 0.7 0.8 0.9 1 1.3333 1.666 2 2.5 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20],...
    'XScale','log',...
    'XMinorTick','on',...
    'XAxisLocation','top',...
    'Position',[0.0390625 0.861340448264463 0.94921875 0.0001]);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.4 20]);

% Create xlabel
xlabel('Period [min]','VerticalAlignment','bottom');

% Create axes
axes2 = axes('Parent',figure1,...
    'XTickLabel',{'0.4','0.5','0.6','0.7','0.8','0.9','1','1.333','1.666','2','2.5','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20'},...
    'XTick',[0.4 0.5 0.6 0.7 0.8 0.9 1 1.3333 1.666 2 2.5 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20],...
    'XScale','log',...
    'XMinorTick','on',...
    'XMinorGrid','on',...
    'Position',[0.0390625 0.05632 0.94921875 0.800674380165289]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes2,[0.4 20]);
grid(axes2,'on');

% Create line
line(XData1,YData1,'Parent',axes2,'Color',cor_color);

% Create xlabel
xlabel('Frequency [cph]');

% Create ylabel
ylabel('Log_{10} Spectra [ cm^2 cph^{-1} ]');

% Create title
title('Welch Periodogram','LineWidth',1,'FontSize',16);

